Repository thegabriele97/WaterIoT, pull requests merged in 2022-04, with the labels that each got.

#16 Telegram Manager
  src/docker-compose.yml
  src/services/deviceconfig/app.py
  src/services/deviceconfig/confs.json
  src/services/openweatheradaptor/app.py
  src/services/telegram/Dockerfile
  src/services/telegram/Makefile
  src/services/telegram/SuperTelepotBot.py
  src/services/telegram/TelMan.py
  src/services/telegram/app.py
  src/services/telegram/data.json
  src/services/telegram/encryption.py
  src/services/telegram/settings.json
Labels: enhancement

#42 Telegram: get sensors data message now extracts the useful values
  src/services/telegram/TelMan.py
Labels: fix

#30 Faster DockerFile: copy only the service's file
  src/services/arduinodevconn/Dockerfile
  src/services/calculator/Dockerfile
  src/services/catalog/Dockerfile
  src/services/example/Dockerfile
  src/services/openweatheradaptor/Dockerfile
  src/services/raspberrydevconn/Dockerfile
  src/services/telegram/Dockerfile
  src/services/thingspeakadaptor/Dockerfile
Labels: fix

#44 Telegram: added /status command
  src/common/CatalogRequest.py
  src/services/telegram/TelMan.py
  src/services/telegram/settings.json
Labels: enhancement

#45 Watering Control
  .github/workflows/docker-image.yml
  src/common/CatalogRequest.py
  src/common/JSONManager.py
  src/common/LinkItem.py
  src/common/Links.py
  src/common/Utils.py
  src/docker-compose.yml
  src/services/arduinodevconn2/settings.json
  src/services/catalog/app.py
  src/services/catalog/settings.json
  src/services/deviceconfig/app.py
  src/services/deviceconfig/confs.json
  src/services/raspberrydevconn/app.py
  src/services/telegram/TelMan.py
  src/services/telegram/app.py
  src/services/telegram/data.json
  src/services/telegram/settings.json
  src/services/thingspeakadaptor/app.py
  src/services/wateringcontrol/Dockerfile
  src/services/wateringcontrol/Makefile
  src/services/wateringcontrol/app.py
  src/services/wateringcontrol/settings.json
  src/services/wateringdatabase/Dockerfile
  src/services/wateringdatabase/Makefile
  src/services/wateringdatabase/app.py
  src/services/wateringdatabase/database.json
  src/services/wateringdatabase/settings.json
Labels: enhancement

#32 Use of uptime-kuma as a service in WaterIoT
  src/docker-compose.yml
  src/services/arduinodevconn/app.py
  src/services/deviceconfig/app.py
  src/services/uptime/Dockerfile
  src/services/uptime/kuma.db
Labels: enhancement

#48 cleanup: removed calculator and example services
  src/docker-compose.yml
  src/services/nodered/flows.json
  utils/oldserv/calculator/Dockerfile
  utils/oldserv/calculator/Makefile
  utils/oldserv/calculator/app.py
  utils/oldserv/calculator/settings.json
  utils/oldserv/example/Dockerfile
  utils/oldserv/example/Makefile
  utils/oldserv/example/app.py
  utils/oldserv/example/settings.json
Labels: fix

#49 Update README.md
  README.md
Labels: documentation
